### ISSUE TITLE
DiskLocked

### ISSUE THREAD

**Issue by Stormlund** [FSLogix/Invoke-FslShrinkDisk#10]
Hi Jim

I've looked through the other "DiskLocked" issues reported, but they don't seem to apply.
Our profile container vhdx's are created by fslogix, and the profiles are working just fine, but the script seems to believe that most of our profiles are locked.
Out of 2368 profiles, 1774 where reported "DiskLocked" at nighttime saturday when the script was run. At that time no more than a maximum of 50 user sessions where active.
I can copy the user vhdx to another location, but even then the script will report "DiskLocked", so I know for sure that's not the case.
However it seems to differ which disks are reported locked from one week to the next, and when I have tested with a copy of a locked .vhdx, the DiskLocked situation will be fixed if I mount/eject the .vhdx
Do you have any advice?

ps. the remaining 594 profiles where handled/compressed as expected

Best regards
Dannie

**Comment by JimMoyle** [comment]
So I've just added better error reporting to the script please redownload and try again.

**Comment by Stormlund** [comment]
Thank you so much for looking into this :-)

I'll use the updated script for next run and let you know how it turns out

/Dannie

**Comment by MeanDoubleStain** [comment]
I have the same issue, where with the old script I got "DiskLocked", Now I have "Failed to read partition   information for disk - "The input name "Type" cannot be   resolved to a property." as mentioned in [Issue #12](https://github.com/FSLogix/Invoke-FslShrinkDisk/issues/12). The effect is [issue #9](https://github.com/FSLogix/Invoke-FslShrinkDisk/issues/9)

**Comment by JimMoyle** [comment]
Hi, I'm happy to take a look, you can reach me at the email associated with my github account.

**Comment by MeanDoubleStain** [comment]
Thanks Jim, I will collect some of the CSV, screenshots and send them. If I can provide anything specific, I'd be glad to.

**Comment by Stormlund** [comment]
Hi Jim
Just to let you know, that the updated script seems to run much better
Either that or the change I did to number of threads has cured the problem, I went from 8 to 2 simultaneous actions (throttlelimit)
I actually suspect the original problem to be timing related, so lowering the throttlelimit could be what did the trick

Thank you again :-)
