### ISSUE TITLE
Get-RunspaceData Failed

### ISSUE THREAD

**Issue by sjclarke1965** [FSLogix/Invoke-FslShrinkDisk#17]
Hi Jim - Can you pelase advise on this issue attempting to run script against VHDX file on a UNC path
Get-RunspaceData : Failed
 
Extended information:
The service cannot be started, either because it is disabled or because it has no enabled devices 
associated with it.
 
Activity ID: {017894b9-eb51-45e4-bf22-1b549f350e19}
At C:\Scripts\Invoke-FslShrinkDisk-master\Invoke-FslShrinkDisk.ps1:717 char:13
+             Get-RunspaceData -wait
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (StorageWMI:ROOT/Microsoft/...age/MSFT_Volume) [Write-Error], 
    CimException
    + FullyQualifiedErrorId : StorageWMI 4,Get-RunspaceData

**Comment by JimMoyle** [comment]
So this looks like either the defrag or virtual disk service isn't started on the VM you are running the script from

**Comment by sjclarke1965** [comment]
Hi Jim

thanks for feedback

I have attempted to run script against my o365 share and I have many
VHDX reporting this error

Failed to read partition information for disk - "The input name "Type"
cannot be resolved to a property."

Where as many are also processing but I have no idea why the
discrepancy? could you perhaps shed some light on reasons why this
would be the case?

----- Original Message -----
From: "FSLogix/Invoke-FslShrinkDisk"
<reply@reply.github.com>
To:"FSLogix/Invoke-FslShrinkDisk"
<Invoke-FslShrinkDisk@noreply.github.com>
Cc:"sjclarke1965" <sjclarke1965@optusnet.com.au>, "Author"
<author@noreply.github.com>
Sent:Fri, 18 Sep 2020 13:40:12 +0000 (UTC)
Subject:Re: [FSLogix/Invoke-FslShrinkDisk] Get-RunspaceData Failed
(#17)

	So this looks like either the defrag or virtual disk service isn't
started on the VM you are running the script from 

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2]. 
-------------------------
Email sent using Optus Webmail

Links:
------
[1]
https://github.com/FSLogix/Invoke-FslShrinkDisk/issues/17#issuecomment-694873924
[2]

**Comment by JimMoyle** [comment]
This is usually the case where the script is being run form an underpowered machine, the default number of threads is 8.

If you are having issues either add more and faster cores, or restrict the thread count to the number of cores you have. If you still see the issue set the throttle limit to 1 and see where that gets you.

**Comment by sjclarke1965** [comment]
thanks Jim

----- Original Message -----
From: "FSLogix/Invoke-FslShrinkDisk"
<reply@reply.github.com>
To:"FSLogix/Invoke-FslShrinkDisk"
<Invoke-FslShrinkDisk@noreply.github.com>
Cc:"sjclarke1965" <sjclarke1965@optusnet.com.au>, "Author"
<author@noreply.github.com>
Sent:Sun, 20 Sep 2020 05:00:53 -0700
Subject:Re: [FSLogix/Invoke-FslShrinkDisk] Get-RunspaceData Failed
(#17)

	This is usually the case where the script is being run form an
underpowered machine, the default number of threads is 8. 

	If you are having issues either add more and faster cores, or
restrict the thread count to the number of cores you have. If you
still see the issue set the throttle limit to 1 and see where that
gets you. 

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [1], or unsubscribe
[2]. 
-------------------------
Email sent using Optus Webmail

Links:
------
[1]
https://github.com/FSLogix/Invoke-FslShrinkDisk/issues/17#issuecomment-695779109
[2]
