### ISSUE TITLE
The ampersand (&) character is not allowed

### ISSUE THREAD

**Issue by gerguk** [FSLogix/Invoke-FslShrinkDisk#23]
Hi,

Really appreciate all the work that goes into this :-)

Windows Server 2019 (1809)
Powershell version 5.1 Build 17763 Revision 1432
Containers are stored on this server in:
D:\Containers
   \Office
   \Profile
Running your PS1 file like this from Powershell opened as Administator
`.\Invoke-FslShrinkDisk.ps1 -Path d:\Containers -Recurse -LogFilePath C:\Users\my.name\Downloads\fsl_run1.csv`

I get lots of errors

At C:\users\my.name\Downloads\Invoke-FslShrinkDisk.ps1:151 char:21
+                 Sign&nbsp;up
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\users\my.name\Downloads\Invoke-FslShrinkDisk.ps1:178 char:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\users\my.name\Downloads\Invoke-FslShrinkDisk.ps1:178 char:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+

Quite likely I'm doing something wrong!

Many thanks,
Greg

**Comment by gerguk** [comment]
Hmmm, formatting is a bit rubbish so trying again!

```
At C:\users\my.name\Downloads\Invoke-FslShrinkDisk.ps1:151 char:21
                 Sign&nbsp;up
                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\users\my.name\Downloads\Invoke-FslShrinkDisk.ps1:178 char:190
 ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
                                                                 ~
The '<' operator is reserved for future use.
At C:\users\my.name\Downloads\Invoke-FslShrinkDisk.ps1:178 char:261
 ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
```

**Comment by JimMoyle** [comment]
So that code isn't in my script, can you re-download and try it again?

**Comment by gerguk** [comment]
Sorry about that Jim. I downloaded and extracted the Zip and all good now :-)
