### ISSUE TITLE
PARAMETER LogFilePath should use the default filename for csv file

### ISSUE THREAD

**Issue by dewildep** [FSLogix/Invoke-FslShrinkDisk#29]
Hi, the default location for this csv file is the user’s temp directory. The default filename is in the following format: FslShrinkDisk 2020-04-14 19-36-19.csv
This is great and gives the opportunity to quickly get back to a specific run.
But when i specify -LogFilePath "C:\Scripts\Logs" this does not work. -LogFilePath "C:\Scripts\Logs\logfile.csv" does work. I would like to just specify the Path to place the log files, like the default setting, and get date/time filename based csv files.

Is that possible?

**Comment by JimMoyle** [comment]
You can replicate the script name by doing the following:

 -LogFilePath "C:\Scripts\Logs\FslShrinkDisk $(Get-Date -Format yyyy-MM-dd` HH-mm-ss).csv"

I hope that works for you
