### ISSUE TITLE
DiskState: Succes but vhdx remains same size

### ISSUE THREAD

**Issue by hmbooms** [FSLogix/Invoke-FslShrinkDisk#3]
Hi,
I do not know if this is script related but I ran the script against a FSLogix Profile_<username>.vhdx but the vhdx is not being resized/shrunk.

Command: Invoke-FslShrinkDisk.ps1 -Path Profile_<username>.vhdx -PassThru
Result:
DiskState: Success
OriginalSizeGB : 7.88
FinalSizeGB: 7.88
SpaceSavedGB: 0

I mounted the vhdx file and the size is only around 500MB (I downloaded some file and removed them after).

Is there a way to troubleshoot this? I think it has something to do with the resize of the disk.

**Comment by JimMoyle** [comment]
Hi hmbooms, 

I just updated the script, can you retest if possible?

**Comment by hmbooms** [comment]
Hi Jim,
Thanks for the quick reply. Great, it works. Thanks

Grtz,
Hans
