### ISSUE TITLE
WARNING: Failed to delete temp mount directory

### ISSUE THREAD

**Issue by gerthansendk** [FSLogix/Invoke-FslShrinkDisk#37]
Hey Jim
Fantastic script. Great job!

When I ran the script from differens locations, for example directly from the SOFS I got following Warning after the Shrink job has runned. The job running successfully, but the warning keep coming and feeling up my Temp folder on the server

![image](https://user-images.githubusercontent.com/44923933/111332711-4eb7e380-8672-11eb-906f-612f99ed9466.png)
![image](https://user-images.githubusercontent.com/44923933/111332991-8aeb4400-8672-11eb-8afd-2f3c5fdf6d64.png)

Have checked access to the location with my used account
What do I wrong :-)

Thanks in advance
Gert Hansen - DK

**Comment by JimMoyle** [comment]
So I try a number of different ways to delete this directory,  it doesn't affect then working of the script.  What kind of VM are you running it from?  OS/CPU/RAM

**Comment by gerthansendk** [comment]
Thanks Jim for your feedback and deeply sorry I newer responded... Lets keep it closed until I get it tested.

**Comment by Uttern69** [comment]
Hi, 
I'm having the exact same problem.
OS Windows Server2019, 6vCPUs, 32GB RAM
Best regards
Jonas

**Comment by Uttern69** [comment]
It's everyone.
I have only tested about 10 vhdx-files, but with the same error every time.

Den tors 23 mars 2023 kl 16:11 skrev Jim Moyle ***@***.***>:
