### ISSUE TITLE
QUERY: Export whitespace % without shriking VHDs

### ISSUE THREAD

**Issue by nmunkley** [FSLogix/Invoke-FslShrinkDisk#44]
Hi

Is it possible to export the current whitespace % for each VHD into a CSV to be used to quantify running the full script? I work in an environment with thousands of users and have been asked to provide evidence to quantify running the script. Is it possible to have a pass where it collects the data including % whitespace but does not shrink any VHDs?

**Comment by JimMoyle** [comment]
Not right now, it's on the roadmap to provide a '-whatif' function.

Usually the first run will save 50-90% space.

Jim

**Comment by nmunkley** [comment]
Thanks for confirming. That will be handy when it is available. I have already run this once before on one FSlogix data store and need to run it on a 2nd. But part of ongoing maintenance is to keep on top of this, so -whatif can be run monthly and then only run the full when it will provide a reasonable return as it took several hours the first time.

**Comment by JimMoyle** [comment]
It shouldn't take several hours.

Run it remotely from a Windows 10/ 2019 machine, give the machine lots of
CPU cores and set the throttle limit to double the amount of cores should
really shorten your run time.

Jim
