### ISSUE TITLE
Feature Request - get large files inside vhdx

### ISSUE THREAD

**Issue by AlexanderFaller** [FSLogix/Invoke-FslShrinkDisk#46]
Hello,
the tool works great.
Maybe it would also be helpful to get an overview of the largest files within larger VHDX?
To see if there are perhaps duplicate OST files that have not been deleted by fslogix or if, for example, the search database is oversized.

**Comment by MrFly72** [comment]
One File-Area I already cleanup now is RoamCache-Files. These tend to get more over time and have multiple older versions in stock. Thats what I found for an example inside of Office-Containers.
Additionally I cleanup OST Files that are too old and NST Files which seem to get stuck also.
So its definitely worth to look inside. 
There is also an possibility to look for these files by running a login-script in the user context and look for "anomalies"

**Comment by JimMoyle** [comment]
FSLogix has the ability to natively delete orphaned ost files on logout anyway.

I'm not going to add the ability to clean other files from within my tool as there are many others who do that job and it could really hurt performance to delete caches.

**Comment by MrFly72** [comment]
Don’t get me wrong. I delete only orphaned NST and Roamcache Files and they are at the moment not deleted. Is it an additional setting in FSLogix?

**Comment by JimMoyle** [comment]
https://docs.microsoft.com/en-us/fslogix/profile-container-configuration-reference#removeorphanedostfilesonlogoff

**Comment by lordjeb** [comment]
This setting should cleanup orphaned NST files as well as OST files in the more recent versions of FSLogix.

**Comment by AlexanderFaller** [comment]
okay thank you all for your help!
I will have a look at the solutions above.
