### ISSUE TITLE
Does nothing?

### ISSUE THREAD

**Issue by sgealbhain** [FSLogix/Invoke-FslShrinkDisk#47]
Hey guys,

I'd like to use this script, but when I run it, it mounts the VHD then just bombs out with no error. Any ideas?

Thanks

**Comment by JimMoyle** [comment]
Are these 3 services running?
'defragsvc', 'vds', 'smphost'

**Comment by JimMoyle** [comment]
Also the script works best when run from a remote machine, try running from a regular Win10 VM

**Comment by sgealbhain** [comment]
Thanks Jim. Looks like this was related to the Storage Spaces service being disabled. The script seemed to do more this time and the VHD is smaller. Is it normal for the script to provide no output?

**Comment by JimMoyle** [comment]
All powershell scripts shouldn't produce pipeline output on success.  It
does produce a log file in your temp folder (you can change the location).
You can also create a pipeline object by specifying the -passthru parameter

Jim
