### ISSUE TITLE
Where to amend?

### ISSUE THREAD

**Issue by sgealbhain** [FSLogix/Invoke-FslShrinkDisk#48]
Hi Jim,

I need to insert some code that removes cached OneDrive files not accessed within the last 30 days. I have the line of code that does this piece, but I'm wondering where to insert it in your script?

The logic would be quite simple. 

1) The VHD is mounted
2) The OneDrive function runs
3) Once the files have been removed, the remainder of your script can run to shrink the VHD and unmount.

Thanks in advance!

**Comment by JimMoyle** [comment]
I'd do it after the '#Initial disk Mount' try/catch block in the optimize onedisk function this appears in two places and is called depending on which version of powershell you are using.

If you are trying to save space I'd enact storage sense and files on demand rather than doing this. (2019 or Win10)

If you are on 2016 I'd dehydrate the files rather than deleting them you can do this with powershell.

Jim

**Comment by sgealbhain** [comment]
So when I use $mount.path it gives me a long string rather than a temp drive letter. Like this: Mnt-aaed3d12-f59e-44e1-9aca-14f8210c354

Is there a way to access this or a way to reference the temp drive letter?

**Comment by JimMoyle** [comment]
I don't use drive letters as if someone is using 30 threads to shrink disks
there are only 26 letters in the alphabet and this would obviously cause
issues, you can access the drive contents via the path.

Jim

**Comment by sgealbhain** [comment]
Makes sense Jim. So I want to access \OneDrive\Contents so how would I specify the full path to that using the temp path? I have tried $path = "$($mount.path)\OneDrive\files\Business1\PSTools" but that doesn't work. If I write out the contents of $mount it gives me 

@{Path=C:\Users\stephen\AppData\Local\Temp\FSLogixMnt-db8b3eb5-9915-488d-bae1-bcee96964ee1; DiskNumber=2; ImagePath=E:\fslogix\S-1-5-21-7145671942-14888194-2018343319-7689899_t612\ODFC_t612.VHDX; PartitionNumber=1}

**Comment by sgealbhain** [comment]
Nevermind I figured it out! Thanks Jim

**Comment by sgealbhain** [comment]
I've added in this code in the Optimtize-OneDisk function. It works as it should but with some vhds I notice I'm getting the below error.

**Get-RunspaceData : Could not find a part of the path** 

`#Initial disk Mount
        try {
            $mount = Mount-FslDisk -Path $Disk.FullName -TimeOut 30 -PassThru -ErrorAction Stop
        }
        catch {
            $err = $error[0]
            Write-VhdOutput -DiskState $err -EndTime (Get-Date)
            return
        }

        ###################################################
        $limit = (Get-Date).AddDays(-30)
        $path = "$($mount.path)\OneDrive\files\Business1\"
        New-PSDrive "X" -PSProvider FileSystem -Root "$path"
        Start-Transcript -Path "X:\SCRIPT_Transcript.txt" -NoClobber
        # Delete files older than the $limit.
        $OneDriveFiles = Get-ChildItem -Path "X:\" -Recurse -Force | Where-Object { (!$_.PSIsContainer -and $_.LastAccessTime -gt $limit) -and $_.Attributes -notmatch "sparse" } # | Remove-Item -Force
        $OneDriveFiles
        Write-Host $mount -f Yellow

        Stop-Transcript -Path "X:\SCRIPT_Transcript.txt" -NoClobber

        ###################################################

        #Grabbing partition info can fail when the client is under heavy load so.......`

**Comment by JimMoyle** [comment]
OK so remember I don't approve of you doing this.......

But the disk is already mounted to the path, why are you trying to double mount it to a drive letter?   I'd also create variables which will be unique to you unless you can be sure I have not used '$path' elsewhere.

The script is running in a runspace so you won't see write-host it's just slowing everything down and you are writing the transcript to the folder you are reading.

I'd do something more like this:

```
    $sgLimit = (Get-Date).AddDays(-30)
    $sgPath = Join-Path $mount.path 'OneDrive\files\Business1'
    Start-Transcript -Path "$env:Temp\SGlog.txt" -NoClobber
    # Delete files older than the $limit.
    Get-ChildItem -Path $sgPath -Recurse -Force | Where-Object { (!$_.PSIsContainer -and $_.LastAccessTime -gt $limit) -and $_.Attributes -notmatch "sparse" } # | Remove-Item -Force
    Stop-Transcript -Path "$env:Temp\SGlog.txt" -NoClobber
```

**Comment by sgealbhain** [comment]
Ah yes, let me give this a try! The reason for the double mount is because I thought it was having problems with the the long file path. I'll try out your suggestion. Thanks, Jim!

**Comment by sgealbhain** [comment]
Getting the same thing with your suggestion also I'm afraid. I'm wondering if its the length of the overall path? Maybe not?

Get-RunspaceData : Could not find a part of the path 
'C:\Users\AutoAdmin\AppData\Local\Temp\FSLogixMnt-79ba688772f-40f3-8edc-6e8f5c3bc\OneDrive\files\Business1\_Existing\320Drive\Supp\Ben 
\CompleteViewSupport\jakarta-jmeter-2.3.2\docs\api\org\apache\jmeter\protocol\ldap'.
At C:\Scripts\Invoke-FslShrinkDisk-master\Invoke-FslShrinkDisk-master\Invoke-FslShrinkDisk.ps1:758 char:13
+             Get-RunspaceData -wait
+             ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\Users\Automa...r\protocol\ldap:String) [Write-Error], DirectoryNotFoundException
    + FullyQualifiedErrorId : DirIOError,Get-RunspaceData

**Comment by JimMoyle** [comment]
So to debug a runspace you need to put wait-debugger in the script and
attach to the thread

Jim
