### ISSUE TITLE
Script won't run with "Microsoft Storage Spaces SMP" and "Optimize Drives" services in Disabled state

### ISSUE THREAD

**Issue by steveturnbull** [FSLogix/Invoke-FslShrinkDisk#5]
On a highly optimised Windows Server 2016 build, the invoke-fslshrinkdisk script would not run correctly.

It would throw an error :  
**Get-RunspaceData : No MSFT_Partition objects found with property 'DiskNumber' equal to '1'.**

The script requires the following two services to be set to manual state so they can be started up on demand.  They start when the script is running and we had these services set to disabled.

"Microsoft Storage Spaces SMP"
"Optimize Drives"

**Comment by JimMoyle** [comment]
Thanks for writing this up Steve.
