### ISSUE TITLE
Fails in importing this module into Azure Automation account

### ISSUE THREAD

**Issue by NIHandrew** [FSLogix/Invoke-FslShrinkDisk#50]
I guest the following error when trying to add this module to my Azure Automation Account - it happens in both Runtime ver 5.1 and 7.1(preview):

Error importing the module Invoke-FslShrinkDisk-master. Import failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: Cannot import the module of name Invoke-FslShrinkDisk-master, as the module structure was invalid. at Orchestrator.Activities.GetModuleMetadataAfterValidationActivity.ExecuteInternal(CodeActivityContext context, Byte[] moduleContent, String moduleName, ModuleLanguage moduleLanguage) at Orchestrator.Activities.GetModuleMetadataAfterValidationActivity.Execute(CodeActivityContext context) at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager) at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)

**Comment by JimMoyle** [comment]
Unfortunately It needs admin access to mount and then defrag the internal partition. neither admin access or mounting are permissible inside an automation account.

If you do find a way to make it work, I'd be extremely interested in the solution.

**Comment by drijj** [comment]
Hi There, 

I was playing with Azure Automation Account and this script to let it work.
It is Possible to mount and defrag if you use a hybrid worker. 

See this is the output of my mount action en optimize-volume. 
Attached          : True
BlockSize         : 33554432
DevicePath        : \\.\PHYSICALDRIVE3
FileSize          : 1782579200
ImagePath         : p:\xxxxxxxx\Profile_xxxx.VHDX
LogicalSectorSize : 512
Number            : 3
Size              : 31457280000
StorageType       : 3
PSComputerName    : 
Invoking slab consolidation on Profile_xxxx
Slab Analysis:  0% complete...
Slab Analysis:  100% complete.  
Retrim:  100% complete.  

	Slab consolidation was skipped because there were few evictable slabs.

Post Defragmentation Report:

	Volume Information:
		Volume size                 = 29.29 GB
		Cluster size                = 4 KB
		Used space                  = 1.28 GB
		Free space                  = 28.00 GB

	Allocation Units:
		Slab count                  = 936
		Slab size                   = 32 MB
		Slab alignment              = 31.00 MB
		In-use slabs                = 49

	Slab Consolidation:
		Space efficiency            = 100%
		Potential purgable slabs    = 0
		Slabs pinned unmovable      = 6
		Successfully purged slabs   = 0
		Recovered space             = 0 bytes

	Retrim:
		Backed allocations          = 49
		Allocations trimmed         = 0
		Total space trimmed         = 0 bytes
Attached          : False
BlockSize         : 33554432
DevicePath        : 
FileSize          : 1782579200
ImagePath         : p:\xxxxxxxx\Profile_xxxx.VHDX
LogicalSectorSize : 512
Number            : 
Size              : 31457280000
StorageType       : 3
PSComputerName    :
