### ISSUE TITLE
Cannot run tool with Constrained Language mode

### ISSUE THREAD

**Issue by brmcmill** [FSLogix/Invoke-FslShrinkDisk#56]
Ran into this issue while trying to run this tool in `ConstrainedLanguage` mode.

![image](https://user-images.githubusercontent.com/26752719/156822495-861e04a6-05ec-4278-a06d-70a18c2bc838.png)

**Comment by JimMoyle** [comment]
Hi, I've never tested constrained language mode and hence don't support it.

However it looks like you are using 5.1 not PowerShell 7.x. I use a different method for multi threading which might not cause the same issues.

**Comment by brmcmill** [comment]
Thanks @JimMoyle!  I'll test out 7.x in this situation and follow up!  Appreciate the response.

**Comment by brmcmill** [comment]
Hey @JimMoyle  -- looks like this should work with PowerShell v7.  Tested it out in my lab on a few containers.  Apologies for the delay on following up!  I'll close this.
