### ISSUE TITLE
Disklocked

### ISSUE THREAD

**Issue by ccautaerts** [FSLogix/Invoke-FslShrinkDisk#6]
I get always the disklocked , tried several times mount/unmount of the vhdx and that works without a problem. 
If I mount the file it is using only 1.2GB, but the size on the fileshare shows 5.5 GB. I've attached the logfile.
[hoesi..txt](https://github.com/FSLogix/Invoke-FslShrinkDisk/files/4903821/hoesi.txt)

**Comment by ccautaerts** [comment]
Did anyone experience the same behavior?
Any suggestions please?

**Comment by JimMoyle** [comment]
What happens when you run these commands against the vhd?

$path = <path to vhd>
$mountedDisk = Mount-DiskImage -ImagePath $Path -NoDriveLetter -PassThru -ErrorAction Stop | Get-DiskImage
$partition = Get-Partition -DiskNumber $mountedDisk.Number | Where-Object -Property 'Type' -eq -Value 'Basic'
        $tempGUID = [guid]::NewGuid().ToString()
        $mountPath = Join-Path $Env:Temp ('FSLogixMnt-' + $tempGUID)
New-Item -Path $mountPath -ItemType Directory -ErrorAction Stop
            $addPartitionAccessPathParams = @{
                DiskNumber      = $mountedDisk.Number
                PartitionNumber = $partition.PartitionNumber
                AccessPath      = $mountPath
                ErrorAction     = 'Stop'
            }

            Add-PartitionAccessPath @addPartitionAccessPathParams

**Comment by ccautaerts** [comment]
Hi Jim, thanks for reply.
I've executed above commands and the $partition result is empty as in the error below:
PS C:\tools\FSLogix_Tools\Invoke-FslShrinkDisk-master> Add-PartitionAccessPath @addPartitionAccessPathParams
Add-PartitionAccessPath : Cannot validate argument on parameter 'PartitionNumber'. The argument is null. Provide a vali
d value for the argument, and then try running the command again.
At line:1 char:25
+ Add-PartitionAccessPath @addPartitionAccessPathParams
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-PartitionAccessPath], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Add-PartitionAccessPath

Although Diskmanager shows an active partition:
![image](https://user-images.githubusercontent.com/37797636/87910042-a2cde200-ca69-11ea-8046-5f162de695ff.png)

However if I run the command :$partition = Get-Partition -DiskNumber $mountedDisk.Number
it does show a result:
PS C:\tools\FSLogix_Tools\Invoke-FslShrinkDisk-master> $partition
   DiskPath: \\?\scsi#disk&ven_msft&prod_virtual_disk#2&1f4adffe&0&000001#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}

PartitionNumber  DriveLetter Offset                                        Size Type
---------------  ----------- ------                                        ---- ----
1                            1048576                                      30 GB IFS

**Comment by ccautaerts** [comment]
Sorry missed  comment button.

**Comment by JimMoyle** [comment]
So the IFS thing is the problem, did this disk get made by the FSlogix agent or another method?

**Comment by ccautaerts** [comment]
Hi Jim,
I’ ve used the script from David Odd to do the conversion from Citrix UPM to FSLogix, and so far it all works fine. The thing is if you use diskpart to create an extensible vdisk it just uses IFS.
What I’ve tried is, in your script replace all the -value ‘basic’  by -value’IFS’ and seemed to work at first sight, I mean I can reduce the excessive disk space usage (which is generated by Microsoft Teams installation directly into the profile).
But I’m not sure if the profile is still working fine. I could not test it. But I’l give it a try tomorrow (today is national holliday in Belgium 😊 ).

Thank you,
Christian


Christian Cautaerts | Consultant

Getronics
________________________________
T. +3222299313 | M. +32 477 684 054 | E. Christian.Cautaerts@Getronics.com | W. www.getronics.com
P Please consider the environment before printing this e-mail


Getronics Belgium nv De Kleetlaan 12B, 1831 Diegem,Belgium RPR Brussel/RPM Bruxelles BTW/TVA BE 0424 104 685

The information transmitted is intended only for use by the addressee and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of it, or the taking of any action in reliance upon this information by persons and/or entities other than the intended recipient is prohibited. If you received this in error, please inform the sender and/or addressee immediately and delete the material.Please note that this e-mail is also subject to the following disclaimer: http://www.getronics.com/legal/.

**Comment by JimMoyle** [comment]
Yeah the script is designed to work with FSLogix disks, if you create the disks with other tools it's not going to do what you want.

I'm glad you found a workaround for use with diskpart disks.
