### ISSUE TITLE
Corrupted .vhdx Files in the Wake of Shrink Operation

### ISSUE THREAD

**Issue by WGamradt** [FSLogix/Invoke-FslShrinkDisk#8]
Hello,

I have been having issues post execution where some of the vhdx files appear to be corrupted upon completion. This is seen by the users reporting out of space issues shortly after the shrink operation.

In my environment we set the FSL container as dynamic with a size of 150GB. Users have been experiencing issues even though the actual size may only be 6GB or so.

![image](https://user-images.githubusercontent.com/26904846/88399400-6ca3a180-cd8c-11ea-88f4-aebbcfe730b8.png)

I have tried mounting an affected vhdx and running chkdsk against them. It does report an error but even though it reportedly fixes the problem the issue remains.
![image](https://user-images.githubusercontent.com/26904846/88399559-ac6a8900-cd8c-11ea-8386-c185aadc5075.png)

It appears that the structure of the internal file system has some way or another been corrupted. Have you been seeing issues such as this?

The environment we have is using a Server 2012R2 instance for the FSL share and all RDSH systems are Server 2016.

Thanks in advance.

**Comment by JimMoyle** [comment]
Not seen this reported before, but I'd love to be able to test against the vhdx.  Do you have a disk I can test against which doesn't have real user data inside?

**Comment by JimMoyle** [comment]
Also what does the output file say?

**Comment by JimMoyle** [comment]
Hi, any update on this?

**Comment by JimMoyle** [comment]
Closing this issue due to lack of updates
