### ISSUE TITLE
Stops After shrinking 1 or 2 VHDXs

### ISSUE THREAD

**Issue by WakeGSY** [FSLogix/Invoke-FslShrinkDisk#9]
Hi Jim,

Thanks for the Script, Great job!

I am having a couple of problems probably me and not the script but I would much appreciate your help!

I have made no changes to the script and running the following:
PS C:\> .\Invoke-FslShrinkDisk.ps1 -path "\\internal\data\fslogixprofiles" -Recurse -LogFilePath C:\Logman8_4.csv -IgnoreLessThanGB 8

We have over 900 VHDXs in this directory and it picks them all up but the script terminates after shrinking 1 or 2 of them. I run the same command again and it shrinks another 1 or 2. Running the command manually over and over gets the space down but Ideally, I want to run this unattended.

I doubt its related but I also get the following output in the shell:
WARNING: Failed to delete temp mount directory
C:\Users\ADMIN~1.ROS\AppData\Local\Temp\133\FSLogixMnt-2f7dc7d5-0284-4e10-bc3f-803358570639
WARNING: Failed to delete temp mount directory
C:\Users\ADMIN~1.ROS\AppData\Local\Temp\133\FSLogixMnt-8e6253ad-94c9-43fb-9420-5f996a7194c7
Get-RunspaceData : An object at the specified path C:\Users\ADMIN~1.ROS does not exist.
At C:\ITAdmin\scripts\FSLogixShrinkDisk\Invoke-FslShrinkDisk.ps1:725 char:21
+                     Get-RunspaceData
+                     ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Write-Error], PSArgumentException
    + FullyQualifiedErrorId : Argument,Get-RunspaceData

Thanks

Ross

**Comment by JimMoyle** [comment]
Hi Ross, I'd like to take a look at this, what timezone are you on?  you can mail me at jim dot moyle at microsoft dot com

**Comment by JimMoyle** [comment]
So I've just added better error reporting to the script please redownload and try again

**Comment by WakeGSY** [comment]
Thanks Jim!

Ryan, are you able to look at this? I'm not back to work for another week

Cheers,

Ross
07781107294

Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by JimMoyle** [comment]
So I've made some changes, adding retries etc. can you test the script i this branch?

https://github.com/FSLogix/Invoke-FslShrinkDisk/tree/Optimize-OneDisk

Thanks

Jim

**Comment by JimMoyle** [comment]
Closing due to non-activity
